"""BaseEnvironment — protocol for execution environments."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from codeminions.core.context import ExecResult


@runtime_checkable
class BaseEnvironment(Protocol):
    path: str

    async def read(self, path: str) -> str: ...
    async def write(self, path: str, content: str) -> None: ...
    async def edit(self, path: str, old: str, new: str) -> None: ...
    async def exec(self, cmd: str, cwd: str | None = None) -> ExecResult: ...
    async def glob(self, pattern: str) -> list[str]: ...
    async def exists(self, path: str) -> bool: ...
    async def cleanup(self) -> None: ...
